### ISSUE TITLE
Example code on how to subscribe to a subset of events

### ISSUE THREAD

**Issue by somini** [Smithay/input.rs#52]
I'm a complete Rust and libinput newbie, please bear with me.

I wrote this program a while back to support Push-To-Talk system-wide.

https://gitlab.com/somini/inpulse-to-talk/-/blob/master/src/bin/inpulse-daemon.rs#L75-92

This is basically a keylogger for a single key, so I subscribe to the firehose and discard all other events. This works, but burns CPU like crazy, and seems all around wasteful. Instead of starting up with the system, I just use it during calls, it's really handy.

In case you did not notice, it's basically the example code with minor tweaks. Includes the changes in #51.

Is there a way to filter the firehose in some way, subscribe only to certain types of events, or device types? Ideally, filtering only for a single keyboard key would be ideal. Or is this the wrong approach?

I know this is possible, because Sway doesn't burn CPU when I'm not using the keyboard, but I'm a complete noob in this low-level interfaces.

**Comment by Drakulix** [comment]
The correct wait to not burn CPU resources is to wait on the file descriptor of the `Libinput` context, so that your process will sleep until new events are ready to be processed, instead of spinning mindlessly in that `loop`.

You can find an example on how to do this on the `Libinput::fd` function: https://docs.rs/input/latest/input/struct.Libinput.html#method.fd.

(Note this function itself is deprecated, you should use `.as_raw_fd()` instead to obtain the file descriptor, but the example code will work the same way.)

**Comment by somini** [comment]
Thank you very much, released v3.0 which uses basically no CPU whatsoever. Here's the commit:

https://gitlab.com/somini/inpulse-to-talk/-/commit/897c5cbc98d34b2d81aa9387bc0912dc36abce91#79222ec9407f961ac9710b60f2733df29c143fd6
